twig_component:
    anonymous_template_directory: 'shared/components/'
    defaults:
        App\Domain\Account\Twig\Components\: 'domain/account/components/'
        App\Shared\Twig\Components\: 'shared/components/'
