twig_component:
    anonymous_template_directory: 'shared/components/'
    defaults:
        App\Domain\Account\Twig\Components\: 'domain/account/components/'
        App\Domain\Assignment\Twig\Components\: 'domain/assigment/components/'
        App\Domain\Budget\Twig\Components\: 'domain/budget/components/'
        App\Domain\PeriodicEntry\Twig\Components\: 'domain/periodic_entry/components/'

        App\Shared\Twig\Components\: 'shared/components/'
